version: '3.8'

services:
  posgresstask:
    image: task_api
    container_name: task_container
    ports:
      - "5041:80"
    build:
      context: .
      dockerfile: PosgressTask/Dockerfile
    networks: 
      - api_network
  db:
    image: postgres:latest
    container_name: api_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres  
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks: 
      - api_network
networks:
  api_network:
    driver: bridge  
    
volumes: 
   db:
    

 
